# Generated by Django 6.0.4 on 2026-05-04 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                (
                    "location_coordinate_lng",
                    models.FloatField(
                        null=True, verbose_name="longitudinal coordinates"
                    ),
                ),
                (
                    "location_coordinate_lat",
                    models.FloatField(
                        null=True, verbose_name="latitudinal coordinates"
                    ),
                ),
                ("description", models.TextField()),
                ("date_start", models.DateField(null=True, verbose_name="start date")),
                ("date_end", models.DateField(null=True, verbose_name="end date")),
            ],
        ),
        migrations.CreateModel(
            name="AlbumItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        help_text="Maker of the camera",
                        max_length=20,
                        verbose_name="camera brand",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Model of the camera",
                        max_length=10,
                        verbose_name="camera model",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        help_text="Maker of the lens",
                        max_length=20,
                        verbose_name="lens brand",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Model of the lens",
                        max_length=40,
                        verbose_name="lens model",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TextBox",
            fields=[
                (
                    "albumitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="portfolio.albumitem",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "col_size",
                    models.IntegerField(
                        default=1,
                        help_text="Number of columns that the box should take up",
                        verbose_name="column size",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("portfolio.albumitem",),
        ),
        migrations.CreateModel(
            name="AlbumItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="order of the items"),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.album",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.albumitem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="album",
            name="items",
            field=models.ManyToManyField(
                help_text="Items of the album (photos and text)",
                through="portfolio.AlbumItems",
                to="portfolio.albumitem",
            ),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "albumitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="portfolio.albumitem",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Relative path to the base image (without resolution suffix)",
                        max_length=200,
                    ),
                ),
                (
                    "available_res",
                    models.JSONField(
                        help_text="List of available resolutions of the image",
                        verbose_name="available resolutions",
                    ),
                ),
                (
                    "description",
                    models.TextField(null=True, verbose_name="description"),
                ),
                (
                    "date_taken",
                    models.DateTimeField(null=True, verbose_name="date taken"),
                ),
                (
                    "focal_length",
                    models.IntegerField(null=True, verbose_name="focal length"),
                ),
                (
                    "focal_length_35",
                    models.IntegerField(
                        help_text="Focal length in 35mm equivalent",
                        null=True,
                        verbose_name="35mm focal length",
                    ),
                ),
                (
                    "exposure_time",
                    models.CharField(
                        help_text="Exposure time of photo",
                        max_length=10,
                        null=True,
                        verbose_name="exposure time",
                    ),
                ),
                (
                    "exposure_compensation",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="exposure compensation",
                    ),
                ),
                (
                    "aperture",
                    models.DecimalField(decimal_places=1, max_digits=4, null=True),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.camera",
                    ),
                ),
                (
                    "lens",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.lens",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("portfolio.albumitem",),
        ),
    ]
