# Generated by Django 6.0.4 on 2026-05-04 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="date_end",
            field=models.DateField(blank=True, null=True, verbose_name="end date"),
        ),
        migrations.AlterField(
            model_name="album",
            name="date_start",
            field=models.DateField(blank=True, null=True, verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="album",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="album",
            name="location_coordinate_lat",
            field=models.FloatField(
                blank=True, null=True, verbose_name="latitudinal coordinates"
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="location_coordinate_lng",
            field=models.FloatField(
                blank=True, null=True, verbose_name="longitudinal coordinates"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="aperture",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="available_res",
            field=models.JSONField(
                blank=True,
                help_text="List of available resolutions of the image",
                verbose_name="available resolutions",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="camera",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio.camera",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="date_taken",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="date taken"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="description",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="exposure_compensation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="exposure compensation",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="exposure_time",
            field=models.CharField(
                blank=True,
                help_text="Exposure time of photo",
                max_length=10,
                null=True,
                verbose_name="exposure time",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="focal_length",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="focal length"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="focal_length_35",
            field=models.IntegerField(
                blank=True,
                help_text="Focal length in 35mm equivalent",
                null=True,
                verbose_name="35mm focal length",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="lens",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio.lens",
            ),
        ),
        migrations.AlterModelTable(
            name="album",
            table="albums",
        ),
        migrations.AlterModelTable(
            name="albumitems",
            table="album_items",
        ),
        migrations.AlterModelTable(
            name="camera",
            table="cameras",
        ),
        migrations.AlterModelTable(
            name="image",
            table="images",
        ),
        migrations.AlterModelTable(
            name="lens",
            table="lenses",
        ),
        migrations.AlterModelTable(
            name="textbox",
            table="text_boxes",
        ),
    ]
