# Generated by Django 6.0.4 on 2026-05-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_album_date_end_alter_album_date_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
