# Generated by Django 6.0.4 on 2026-05-05 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_album_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "order",
                    models.IntegerField(
                        default=0, verbose_name="order of the category"
                    ),
                ),
            ],
            options={
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "coordinate_lng",
                    models.FloatField(
                        blank=True, null=True, verbose_name="longitudinal coordinates"
                    ),
                ),
                (
                    "coordinate_lat",
                    models.FloatField(
                        blank=True, null=True, verbose_name="latitudinal coordinates"
                    ),
                ),
            ],
            options={
                "db_table": "locations",
            },
        ),
        migrations.AlterModelOptions(
            name="albumitems",
            options={"ordering": ["order"], "verbose_name_plural": "album items"},
        ),
        migrations.RemoveField(
            model_name="album",
            name="location_coordinate_lat",
        ),
        migrations.RemoveField(
            model_name="album",
            name="location_coordinate_lng",
        ),
        migrations.AlterField(
            model_name="image",
            name="camera",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portfolio.camera",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="lens",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portfolio.lens",
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portfolio.category",
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Event location",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portfolio.location",
            ),
        ),
    ]
