# Generated by Django 6.0.4 on 2026-05-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_category_location_alter_albumitems_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="published",
            field=models.BooleanField(default=True, verbose_name="published"),
        ),
    ]
