# Generated by Django 6.0.4 on 2026-05-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_album_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="max_height",
            field=models.IntegerField(
                default=2000, help_text="Maximum height of the image"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="max_width",
            field=models.IntegerField(
                default=2000, help_text="Maximum width of the image"
            ),
            preserve_default=False,
        ),
    ]
