# Generated by Django 6.0.4 on 2026-05-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_image_max_height_image_max_width"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="albumitems",
            constraint=models.UniqueConstraint(
                fields=("album", "item"), name="unique_album_item"
            ),
        ),
    ]
